Repository kuzzleio/sdk-csharp, pull requests merged in 2019-08, with the labels that each got.

#21 Add Bulk controller and unit tests
  .ci/doc/config.yml
  .ci/doc/templates/default.tpl.cs
  .ci/start_kuzzle.sh
  Kuzzle.Tests/API/Controllers/AdminControllerTest.cs
  Kuzzle.Tests/API/Controllers/BulkControllerTest.cs
  Kuzzle.Tests/API/Controllers/DocumentControllerTest.cs
  Kuzzle.Tests/Kuzzle.Tests.csproj
  Kuzzle.Tests/KuzzleTest.cs
  Kuzzle/API/Controllers/AdminController.cs
  Kuzzle/API/Controllers/BulkController.cs
  Kuzzle/API/Controllers/DocumentController.cs
  Kuzzle/Kuzzle.cs
  Kuzzle/Kuzzle.csproj
  Kuzzle/Utils/QueryUtils.cs
  doc/1/controllers/bulk/import-async/index.md
  doc/1/controllers/bulk/import-async/snippets/import-async.cs
  doc/1/controllers/bulk/import-async/snippets/import-async.test.yml
  doc/1/controllers/bulk/mwrite-async/index.md
  doc/1/controllers/bulk/mwrite-async/snippets/mwrite-async.cs
  doc/1/controllers/bulk/mwrite-async/snippets/mwrite-async.test.yml
  doc/1/controllers/bulk/write-async/index.md
  doc/1/controllers/bulk/write-async/snippets/write-async.cs
  doc/1/controllers/bulk/write-async/snippets/write-async.test.yml
Labels: changelog:new-features

#31 Change expiresIn signatures in LoginAsync and RefreshTokenAsync
  .ci/doc/templates/catch.tpl.cs
  Kuzzle.Tests/API/Controllers/AuthControllerTest.cs
  Kuzzle/API/Controllers/AuthController.cs
  doc/1/controllers/auth/check-token/index.md
  doc/1/controllers/auth/check-token/snippets/check-token.test.yml
  doc/1/controllers/auth/create-my-credentials/snippets/create-my-credentials.cs
  doc/1/controllers/auth/create-my-credentials/snippets/create-my-credentials.test.yml
  doc/1/controllers/auth/credentials-exist/index.md
  doc/1/controllers/auth/credentials-exist/snippets/credentials-exist.test.yml
  doc/1/controllers/auth/delete-my-credentials/index.md
  doc/1/controllers/auth/delete-my-credentials/snippets/delete-my-credentials.test.yml
  doc/1/controllers/auth/get-current-user/snippets/get-current-user.test.yml
  doc/1/controllers/auth/get-my-credentials/snippets/get-my-credentials.test.yml
  doc/1/controllers/auth/get-my-rights/snippets/get-my-rights.test.yml
  doc/1/controllers/auth/get-strategies/snippets/get-strategies.test.yml
  doc/1/controllers/auth/login/index.md
  doc/1/controllers/auth/login/snippets/login.cs
  doc/1/controllers/auth/login/snippets/login.test.yml
  doc/1/controllers/auth/logout/snippets/logout.test.yml
  doc/1/controllers/auth/refresh-token/index.md
  doc/1/controllers/auth/refresh-token/snippets/refresh-token.cs
  doc/1/controllers/auth/refresh-token/snippets/refresh-token.test.yml
  doc/1/controllers/auth/update-my-credentials/snippets/update-my-credentials.test.yml
  doc/1/controllers/auth/update-self/snippets/update-self.test.yml
  doc/1/controllers/auth/validate-my-credentials/snippets/validate-my-credentials.test.yml
Labels: changelog:breaking-changes

#36 Configure an awaiter on tasks returned by QueryAsync
  Kuzzle.Tests/API/Controllers/RealtimeControllerTest.cs
  Kuzzle.Tests/API/KuzzleApiMock.cs
  Kuzzle/API/Controllers/RealtimeController.cs
  Kuzzle/Kuzzle.cs
Labels: changelog:enhancements

#32 Add Document controller documentation
  .ci/doc/templates/default.tpl.cs
  .gitignore
  Kuzzle.Tests/API/Controllers/DocumentControllerTest.cs
  Kuzzle/API/Controllers/DocumentController.cs
  doc/.vuepress
  doc/1/controllers/document/count/index.md
  doc/1/controllers/document/count/snippets/count.cs
  doc/1/controllers/document/count/snippets/count.test.yml
  doc/1/controllers/document/create-or-replace/index.md
  doc/1/controllers/document/create-or-replace/snippets/create-or-replace.cs
  doc/1/controllers/document/create-or-replace/snippets/create-or-replace.test.yml
  doc/1/controllers/document/create/index.md
  doc/1/controllers/document/create/snippets/create.cs
  doc/1/controllers/document/create/snippets/create.test.yml
  doc/1/controllers/document/delete-by-query/index.md
  doc/1/controllers/document/delete-by-query/snippets/delete-by-query.cs
  doc/1/controllers/document/delete-by-query/snippets/delete-by-query.test.yml
  doc/1/controllers/document/delete/index.md
  doc/1/controllers/document/delete/snippets/delete.cs
  doc/1/controllers/document/delete/snippets/delete.test.yml
  doc/1/controllers/document/get/index.md
  doc/1/controllers/document/get/snippets/get.cs
  doc/1/controllers/document/get/snippets/get.test.yml
  doc/1/controllers/document/index.md
  doc/1/controllers/document/m-create-or-replace/index.md
  doc/1/controllers/document/m-create-or-replace/snippets/m-create-or-replace.cs
  doc/1/controllers/document/m-create-or-replace/snippets/m-create-or-replace.test.yml
  doc/1/controllers/document/m-create/index.md
  doc/1/controllers/document/m-create/snippets/m-create.cs
  doc/1/controllers/document/m-create/snippets/m-create.test.yml
  doc/1/controllers/document/m-delete/index.md
  doc/1/controllers/document/m-delete/snippets/m-delete.cs
  doc/1/controllers/document/m-delete/snippets/m-delete.test.yml
  doc/1/controllers/document/m-get/index.md
  doc/1/controllers/document/m-get/snippets/m-get.cs
  doc/1/controllers/document/m-get/snippets/m-get.test.yml
  doc/1/controllers/document/m-replace/index.md
  doc/1/controllers/document/m-replace/snippets/m-replace.cs
  doc/1/controllers/document/m-replace/snippets/m-replace.test.yml
  doc/1/controllers/document/m-update/index.md
  doc/1/controllers/document/m-update/snippets/m-update.cs
  doc/1/controllers/document/m-update/snippets/m-update.test.yml
  doc/1/controllers/document/replace/index.md
  doc/1/controllers/document/replace/snippets/replace.cs
  doc/1/controllers/document/replace/snippets/replace.test.yml
  doc/1/controllers/document/search/index.md
  doc/1/controllers/document/search/snippets/search.cs
  doc/1/controllers/document/search/snippets/search.test.yml
  doc/1/controllers/document/update/index.md
  doc/1/controllers/document/update/snippets/update.cs
  doc/1/controllers/document/update/snippets/update.test.yml
  doc/1/controllers/document/validate/index.md
  doc/1/controllers/document/validate/snippets/validate.cs
  doc/1/controllers/document/validate/snippets/validate.test.yml
  doc/1/core-classes/kuzzle/index.md
  doc/1/core-classes/search-options/index.md
  doc/1/core-classes/search-options/introduction/index.md
  doc/1/core-classes/search-result/index.md
  doc/1/core-classes/search-result/introduction/index.md
  doc/1/core-classes/search-result/next/index.md
Labels: changelog:exclude

#35 Add offline tools documentation
  doc/1/core-classes/kuzzle/properties/index.md
  doc/1/essentials/events/index.md
  doc/1/essentials/offline-tools/index.md
  doc/1/essentials/offline-tools/offline-queue-closed.png
  doc/1/essentials/offline-tools/offline-queue-invalid-auth-no-login.png
  doc/1/essentials/offline-tools/offline-queue-invalid-auth-with-login.png
Labels: changelog:exclude, wip

#33 Add error handling documentation
  Kuzzle.Tests/KuzzleTest.cs
  Kuzzle/API/Response.cs
  Kuzzle/Exceptions/ApiErrorException.cs
  doc/1/abstract-classes/index.md
  doc/1/controllers/index.md
  doc/1/core-classes/index.md
  doc/1/core-classes/kuzzle/query-async/index.md
  doc/1/essentials/error-handling/index.md
  doc/1/essentials/index.md
  doc/1/exceptions/api-error-exception/index.md
  doc/1/exceptions/connection-lost-exception/index.md
  doc/1/exceptions/index.md
  doc/1/exceptions/internal-exception/index.md
  doc/1/exceptions/kuzzle-exception/index.md
  doc/1/exceptions/not-connected-exception/index.md
  doc/1/protocols/index.md
Labels: changelog:exclude

#38 Change DocumentController.MDeleteAsync args and returned value
  Kuzzle.Tests/API/Controllers/DocumentControllerTest.cs
  Kuzzle/API/Controllers/DocumentController.cs
  doc/1/controllers/document/m-delete/index.md
  doc/1/controllers/document/m-delete/snippets/m-delete.cs
Labels: changelog:breaking-changes

#28 Add server controller documentation
  .ci/doc/templates/default.tpl.cs
  doc/1/controllers/server/admin-exists/index.md
  doc/1/controllers/server/admin-exists/snippets/adminExists.cs
  doc/1/controllers/server/admin-exists/snippets/adminExists.test.yml
  doc/1/controllers/server/get-all-stats/index.md
  doc/1/controllers/server/get-all-stats/snippets/getAllStats.cs
  doc/1/controllers/server/get-all-stats/snippets/getAllStats.test.yml
  doc/1/controllers/server/get-config/index.md
  doc/1/controllers/server/get-config/snippets/getConfig.cs
  doc/1/controllers/server/get-config/snippets/getConfig.test.yml
  doc/1/controllers/server/get-last-stats/index.md
  doc/1/controllers/server/get-last-stats/snippets/getLastStats.cs
  doc/1/controllers/server/get-last-stats/snippets/getLastStats.test.yml
  doc/1/controllers/server/get-stats/index.md
  doc/1/controllers/server/get-stats/snippets/getStats.cs
  doc/1/controllers/server/get-stats/snippets/getStats.test.yml
  doc/1/controllers/server/index.md
  doc/1/controllers/server/info/index.md
  doc/1/controllers/server/info/snippets/info.cs
  doc/1/controllers/server/info/snippets/info.test.yml
  doc/1/controllers/server/now/index.md
  doc/1/controllers/server/now/snippets/now.cs
  doc/1/controllers/server/now/snippets/now.test.yml
  doc/1/example/example/index.md
  doc/1/example/example/snippets/example.cs
  doc/1/example/example/snippets/example.test.yml
  doc/1/example/index.md
Labels: changelog:exclude

#37 Add Collection Controller Documentation
  .ci/doc/config.yml
  Kuzzle.Tests/API/Controllers/CollectionControllerTest.cs
  Kuzzle/API/Controllers/CollectionController.cs
  Kuzzle/Enums/CollectionController/DynamicProperty.cs
  Kuzzle/Enums/CollectionController/TypeFilter.cs
  Kuzzle/Kuzzle.csproj
  doc/1/controllers/collection/create/index.md
  doc/1/controllers/collection/create/snippets/create.cs
  doc/1/controllers/collection/create/snippets/create.test.yml
  doc/1/controllers/collection/delete-specifications/index.md
  doc/1/controllers/collection/delete-specifications/snippets/delete-specifications.cs
  doc/1/controllers/collection/delete-specifications/snippets/delete-specifications.test.yml
  doc/1/controllers/collection/exists/index.md
  doc/1/controllers/collection/exists/snippets/exists.cs
  doc/1/controllers/collection/exists/snippets/exists.test.yml
  doc/1/controllers/collection/get-mapping/index.md
  doc/1/controllers/collection/get-mapping/snippets/get-mapping.cs
  doc/1/controllers/collection/get-mapping/snippets/get-mapping.test.yml
  doc/1/controllers/collection/get-specifications/index.md
  doc/1/controllers/collection/get-specifications/snippets/get-specifications.cs
  doc/1/controllers/collection/get-specifications/snippets/get-specifications.test.yml
  doc/1/controllers/collection/index.md
  doc/1/controllers/collection/list/index.md
  doc/1/controllers/collection/list/snippets/list.cs
  doc/1/controllers/collection/list/snippets/list.test.yml
  doc/1/controllers/collection/search-specifications/index.md
  doc/1/controllers/collection/search-specifications/snippets/search-specifications.cs
  doc/1/controllers/collection/search-specifications/snippets/search-specifications.test.yml
  doc/1/controllers/collection/truncate/index.md
  doc/1/controllers/collection/truncate/snippets/truncate.cs
  doc/1/controllers/collection/truncate/snippets/truncate.test.yml
  doc/1/controllers/collection/update-mapping/index.md
  doc/1/controllers/collection/update-mapping/snippets/update-mapping.cs
  doc/1/controllers/collection/update-mapping/snippets/update-mapping.test.yml
  doc/1/controllers/collection/update-specifications/index.md
  doc/1/controllers/collection/update-specifications/snippets/update-specifications.cs
  doc/1/controllers/collection/update-specifications/snippets/update-specifications.test.yml
  doc/1/controllers/collection/validate-specifications/index.md
  doc/1/controllers/collection/validate-specifications/snippets/validate-specifications.cs
  doc/1/controllers/collection/validate-specifications/snippets/validate-specifications.test.yml
Labels: changelog:exclude
